//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMeMobile.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class URIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal URIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookMeMobile.Resources.URIResources", typeof(URIResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/.
        /// </summary>
        internal static string ApiURL {
            get {
                return ResourceManager.GetString("ApiURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reservations?From={0}&amp;To={1}&amp;roomId={2}.
        /// </summary>
        internal static string CurrentRoomURL {
            get {
                return ResourceManager.GetString("CurrentRoomURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available?From={0}&amp;To={1}&amp;HasPolycom={2}&amp;IsLarge={3}.
        /// </summary>
        internal static string EmptyRoomURL {
            get {
                return ResourceManager.GetString("EmptyRoomURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://10.10.40.80:666/.
        /// </summary>
        internal static string IpAdress {
            get {
                return ResourceManager.GetString("IpAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reservation/.
        /// </summary>
        internal static string ReservationDomainURL {
            get {
                return ResourceManager.GetString("ReservationDomainURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to room/.
        /// </summary>
        internal static string RoomDomainURL {
            get {
                return ResourceManager.GetString("RoomDomainURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token.
        /// </summary>
        internal static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
    }
}
